### ISSUE TITLE
fix is_record

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-drafts-resources#134]
## Describe the bug

Pretty sure there was a typo in `is_record`: https://github.com/inveniosoftware/invenio-drafts-resources/blob/master/invenio_drafts_resources/services/records/config.py#L33 

## Expected behavior
`is_record`

**Comment by lnielsen** [comment]
The code is correct as far as I can see. The two record API classes have a property set like this:

```
class Record:
  is_draft = False

class Draft:
  is_draft = True
```
