### ISSUE TITLE
components: create a base component with new methods not existing in records-resources base

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-drafts-resources#139]
Many components implement/inherit from the `invenio-records-resources....ServiceComponent`. However, in many cases (e.g. most of the invenio-rdm-records compoenents) we are implementing a wide range of new more:

- `publish`
- `new_version`
- `edit`

Even if we are somehow following a type of signature, it would be nice to have them defined in a base component (i.e. ` `ServiceComponent`) at invenio-draft-resources level to have things better defined and clear (i.e. know which methods **must** be implemented).

**Comment by lnielsen** [comment]
Agree. Will need a new subclass ``DraftServiceComponent``. Then we  should simply add this component to the used components to test that it defines all methods. This way we're sure that all methods are defined.
