### ISSUE TITLE
celery: refactor task to use service registry

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-drafts-resources#158]
[This task](https://github.com/inveniosoftware/invenio-drafts-resources/blob/master/invenio_drafts_resources/services/records/tasks.py#L25) should use the service registry instead of the current method.

https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/tasks.py#L20

**Comment by fenekku** [comment]
closed via https://github.com/inveniosoftware/invenio-drafts-resources/pull/160
