### ISSUE TITLE
Listing all versions using API does not work unless &allversions=true is added to the query

### ISSUE THREAD

**Issue by apirogov** [inveniosoftware/invenio-drafts-resources#180]
This happens when accessing the versions using https://inveniordm.docs.cern.ch/reference/rest_api_drafts_records/#get-all-versions. Without `allversions=true` it returns only the newest version.

Using unmodified InvenioRDM development instance based on master branch.
Bug can be reproduced with any record that has multiple versions.

**Expected behaviour:** getting all versions as hits, even *without* passing `allversions=true` (as this is implied by the semantics of the request itself, regardless of how it is implemented internally)

**Comment by apirogov** [comment]
This did not make it into v8, right?

**Comment by lnielsen** [comment]
No, it's coming in v9
