### ISSUE TITLE
service: args vs ctx

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-drafts-resources#26]
The service's functions allow passing `*args` and `**kwargs`. However, they are nos used and extra parameters are taken from `resources_requestctx`.

> Should `**kwargs` be removed?

**Comment by fenekku** [comment]
My vote is for removing *args / **kwargs from services. Services should be as clear as possible.

**Comment by fenekku** [comment]
Also I think this was about Resources in the end, which also follow the same theory anyway.
