### ISSUE TITLE
indexing: use `$schemas` field

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-drafts-resources#27]
- Add to schema
- Use for `record_to_index` (fall back to default behaviour).

**Comment by fenekku** [comment]
Revisit invenio-rdm-records' 'invenio_search.mappings' here: https://github.com/inveniosoftware/invenio-rdm-records/blob/master/setup.py#L135 when this is tackled.

**Comment by lnielsen** [comment]
Fixed via IndexField system field.
