### ISSUE TITLE
disable versioning on drafts metadata table

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-drafts-resources#32]
```
delattr(DraftMetadataBase, 'expires_at')
```

or 

```
__versioned__ = None
```

Would not work. The first one would not succeed since the attribute is from the parent class, and removing it from there would disable versioning for records too.

Possible solution: invenio-records to have a versioning mixin

**Comment by lnielsen** [comment]
Invenio-Records by default disables versioning now. What is the exact problem and is it still a problem?

**Comment by ppanero** [comment]
it was that before it was enabled by default, and we wanted to remove for drafts... so I guess this can be closed
