### ISSUE TITLE
file [service]: Implement a service to handle files at draft level

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-drafts-resources#71]
[CodiMD source](https://codimd.web.cern.ch/N8p4gXDOROiPTutnQfkzsg?view)

**Important note**: At this level, *drafts-resources*, some methods might overwrite those form *records-resources* level.

The `FileService` will contain the following methods:

| *Verb*         |          *Endpoint*                              |        *Function*                             |
|:----------------- |:-------------------------------------- |:----------------------------------- |
| GET               | /records/:id/files                     | list(recid)                |
| GET               | /records/:id/files/:key          | get(recid, fileid)       |
| GET               | /records/:id/files/:key/content | retrieve_file_content(recid, fileid)           |
| GET               | /records/:id/draft/files                     | list_draft(recid)                |
| POST              | /records/:id/draft/files               | init_upload(recid)     |
| PUT               | /records/:id/draft/files        | **Do not implement**  |
| DELETE            | /records/:id/draft/files               | delete_all(recid)                   |
| PUT               | /records/:id/draft/files/:key          | update_metadata(recid, fileid)           |
| GET               | /records/:id/draft/files/:key          | get_draft(recid, fileid)       |
| POST              | /records/:id/draft/files/:key          | confirm_upload(recid, fileid)            |
| DELETE            | /records/:id/draft/files/:key          | delete(recid, fileid)                      |
| PUT               | /records/:id/draft/files/:key/content | upload_file_content(recid, fileid) |
| GET               | /records/:id/draft/files/:key/content | retrieve_file_content_draft(recid, fileid)           |

**Comment by slint** [comment]
Closed via #77
